### PR TITLE
Fix marathon

### LINKED ISSUE #2: Add logging for errors during the run
Currently there is no logging for easy individual process step in the benchmarking

### LINKED ISSUE #3: Better handle errors during the run
Currently there is no handling of errors during the run of a benchmark. This needs to be added to the system.

See #2

### LINKED ISSUE #6: Enable early termination
- [x] dirty state
- [x] hyperfine not installed
- [x] commit id, branch, tag not available

### PR DESCRIPTION
**Pull request by ucyo**
- fixes #2 
- fixes #3
- fixes #6 
- Todos
  - [x] Check if hyperfine is installed
  - [x]  Dirty State
  - [x] Unknown commits
  - [x] ~Add tests for different use cases~

### CODE REVIEW

File: src/core.rs [hunk 1]
```diff
@@ -36,13 +40,58 @@ impl Benchmark {
...
+}
+
+fn check_validity_of_strings(vec: &[String]) -> (bool, Vec<String>) {
+    debug!("Commits: {vec:?}");
+    let mut csb = util::get_commit_ids().unwrap();
+    let mut csa = util::get_abbrev_commit_ids().unwrap();
+    let mut cs = util::get_branches().unwrap();
+    cs.append(&mut csa);
+    cs.append(&mut csb);
+    debug!("Commits: {cs:?}");
```
Comment (ucyo) [inline src/core.rs:81]: This is a list of commit ids, branches and tags. This can be separated into its own function.
The order is important for the later search: "tags, branches, commit ids (abbrev), commit ids (full)"

- [ ] Add tags

File: src/core.rs [hunk 2]
```diff
@@ -36,13 +40,58 @@ impl Benchmark {
...
+    let mut not_found = Vec::new();
+    let mut is_ok = true;
+    for v in vec {
+        if cs.iter().any(|s| s == v) {
+            continue;
+        } else {
+            not_found.push(v.clone());
+            is_ok = false;
+        }
+    }
```
Comment (ucyo) [inline src/core.rs:91]: For all commits in configuration -> for all commits+tags+branches -> search if commit is included.
How efficient is this implementation?

File: src/main.rs [hunk 3]
```diff
@@ -30,9 +41,22 @@ fn main() -> std::io::Result<()> {
...
+        } else {
+            let msg = result.stderr;
+            let s = util::to_string(msg);
+            warn!("Run[{label:?}] failed with '{s:?}'");
+            if s.contains("The setup command terminated with a non-zero exit") {
+                eprintln!("[Warning] Run {label:?} failed. Setup failed");
+            }
+            eprintln!("[Warning] Run {label:?} failed. Skipping... -> Hyperfine: {s:?}");
+            eprintln!("[Warning] {cmd:?}");
+        }
```
Comment (ucyo) [inline src/main.rs:59]: Handle errors in the outcome of the command by checking its `status` property. Could this be improved?

File: src/util.rs [hunk 4]
```diff
@@ -24,7 +30,14 @@ pub(crate) fn is_git_dirty() -> std::io::Result<()> {
...
-        Command::new("git").arg("checkout").arg(commit).arg("--quiet").status()?;
+        debug!("Git state changed!");
+        Command::new("git")
+            .arg("checkout")
+            .arg(commit)
+            .arg("--quiet")
+            .status()?;
+    } else {
+        debug!("Git state not changed");
     }
```
Comment (ucyo) [inline src/util.rs:41]: Have to check if checkout worked...

File: src/util.rs [hunk 5]
```diff
@@ -75,22 +96,87 @@ pub(crate) fn write_json_to_disk(json: Value, output: &String) -> std::io::Resul
...
+        let res: Vec<String> = s
+            .split('\n')
+            .map(|s: &str| s[2..].to_string())
+            .filter(|s| !s.contains("remotes"))
+            .collect();
+        Some(res)
+    } else {
+        None
+    }
+}
```
Comment (ucyo) [inline src/util.rs:172]: Add `fn get_tags()`

File: src/core.rs (hunk 1 above)
Comment (ucyo) [reply src/core.rs]: Fixed with e59f5df

File: src/util.rs (hunk 4 above)
Comment (ucyo) [reply src/util.rs:41]: Fixed in e59f5dfd83de4d7713fc96e00b5c4bd3c8989fd1

File: src/util.rs (hunk 5 above)
Comment (ucyo) [reply src/util.rs:171]: Fixed in e59f5dfd83de4d7713fc96e00b5c4bd3c8989fd1

File: src/main.rs (hunk 3 above)
Comment (ucyo) [reply src/main.rs]: Fixed in 7b2da22

File: src/util.rs (hunk 4 above)
Comment (ucyo) [reply src/util.rs]: Fixed in 2729e5c

**Review by ucyo — COMMENTED** [review]
Done
